apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secure-lamprey-java-springboot-development
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/secure-lamprey-java-springboot/overlays/development
    repoURL: https://github.com/rhtap-hub/secure-lamprey-java-springboot-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-dmo-development
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
