apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: secure-lamprey-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-hub/secure-lamprey-java-springboot-gitops